language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
env:
    matrix:
        - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.4 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.5 CYTHON_VERSION=0.23

install:
    - source setup_env.sh 
    #- conda install cython=$CYTHON_VERSION --yes
    #- conda install --yes libgfortran 
    - conda install --yes nose coverage cython
script:
    - git clone https://github.com/hainm/pytraj
    - # openmp
    - cd pytraj
    - python setup.py install
    - export LD_LIBRARY_PATH=/home/travis/build/hainm/TestPytraj/pytraj/cpptraj/lib:$LD_LIBRARY_PATH
    - python runtests.py sim
    - # disable openmp
    - git clean -fdx .
    - rm -rf cpptraj
    - python setup.py install --distable-openmp
    - python runtests.py sim
    - # precythonize
    - git clean -fdx .
    - python ./scripts/cythonize.py
    - conda remove cython --yes
    - python setup.py install

notifications:
  email: false
