language: generic
addons:
  apt:
    packages:
      - gfortran
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
matrix:
    include:
      - { os: osx, env: PYTHON_VERSION=3.5 }

install:
    - source setup_env.sh 
    - conda install --yes nose coverage cython openblas
script:
    # - sh install_pytraj.sh
    - sh build_libcpptraj.sh

notifications:
  email: false
