language: python
env:
    matrix:
        - PYTHON_VERSION=2.7 
        - PYTHON_VERSION=3.3
        - PYTHON_VERSION=3.4 

install:
    - source setup_env.sh 
    - conda install --yes -c pytraj pytraj-dev

script:
    - git clone https://github.com/amber-md/pytraj
    - cd pytraj
    - git clone https://github.com/amber-md/cpptraj
    - python ./runtests.py

notifications:
  email: false
