language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
env:
    matrix:
        - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.4 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.5 CYTHON_VERSION=0.23

install:
    - source setup_env.sh 
    - conda install --yes nose coverage cython openblas libgfortran
script:
    - git clone https://github.com/hainm/pytraj
    - # disable openmp
    - cd pytraj
    - python setup.py install  --disable-openmp
    - export LD_LIBRARY_PATH=/home/travis/build/hainm/TestPytraj/pytraj/cpptraj/lib:$LD_LIBRARY_PATH
    - python runtests.py sim
    - #  openmp
    - git clean -fdx .
    - rm -rf cpptraj
    - python setup.py install
    - pip install -i https://testpypi.python.org/pypi pytraj==1.0.0-beta0
    - python runtests.py sim
    - # pip with cythonized files
    - git clean -fdx .
    - ./devtools/mkrelease
    - conda remove cython --yes
    - cd cpptraj
    - export CPPTRAJHOME=`pwd`
    - cd ../
    - pip install dist/*gz

notifications:
  email: false
