language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libnetcdf-dev
env:
    matrix:
        #- PYTHON_VERSION=2.7 CYTHON_VERSION=0.21
        #- PYTHON_VERSION=3.4 CYTHON_VERSION=0.21

        #- PYTHON_VERSION=2.7 CYTHON_VERSION=0.22
        #- PYTHON_VERSION=3.4 CYTHON_VERSION=0.22

        - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.4 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.5 CYTHON_VERSION=0.23

install:
    - source setup_env.sh 
    - conda install cython=$CYTHON_VERSION --yes
    - conda install --yes -c ambermd lapack
    - conda install --yes libgfortran 
    - ls /home/travis/miniconda/envs/myenv//lib/
script:
    - git clone https://github.com/amber-md/pytraj
    - cd pytraj
    - export PYTRAJHOME=`pwd`
    - git clone https://github.com/amber-md/cpptraj
    - cd cpptraj
    - export MYDIR=$HOME/miniconda/envs/myenv/
    - bash ./configure -shared -openmp --with-netcdf=$MYDIR --with-blas=$MYDIR --with-lapack=$MYDIR  -noarpack gnu
    - make libcpptraj -j4
    - cd $PYTRAJHOME
    - python setup.py install
    - export LD_LIBRARY_PATH=`pwd`/cpptraj/lib:$LD_LIBRARY_PATH
    - python ./runtests.py -simple
    - cd tests
    - pip install nose
    - nosetests -vs

notifications:
  email: false
