language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
env:
    matrix:
      # - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23 OPENMP="--disable-openmp"
      #  - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23 OPENMP=""
      #  - PYTHON_VERSION=3.4 CYTHON_VERSION=0.23
      # - PYTHON_VERSION=3.5 CYTHON_VERSION=0.23
      - { os: osx, env: PYTHON_VERSION=3.5 }

install:
    - source setup_env.sh 
    - conda install --yes nose coverage cython openblas
script:
    # - sh install_pytraj.sh
    - sh build_libcpptraj.sh

notifications:
  email: false
