language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gfortran
    - clang-3.5
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev

matrix:
    include:
      - { os: osx, env: PYTHON_VERSION=3.5 }
      # - { os: osx, env: PYTHON_VERSION=3.4 }
      # - { os: linux, env: PYTHON_VERSION=3.5 }
      # - { os: linux, env: PYTHON_VERSION=3.4 }
      # - { os: linux, env: PYTHON_VERSION=2.7 }

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      brew install netcdf fftw;
    fi

install:
    - gfortran --version
    - g++ --version
    - source setup_env.sh 
    - conda install --yes nose coverage cython openblas
script:
    # - sh install_pytraj_conda_make_docs.sh
    # - sh install_pytraj_conda.sh
    # - sh install_pytraj_pip.sh
    # - sh install_pytraj_source.sh
    - sh install_pysander_conda.sh

notifications:
  email: false
