language: python
env:
    matrix:
        - PYTHON_VERSION=2.7 
        - PYTHON_VERSION=3.3
        - PYTHON_VERSION=3.4 

before_install:
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install gfortran
    - sudo apt-get install -qq libz-dev libbz2-dev

install:
    - source setup_env.sh 
    - conda install --yes -c pytraj pytraj-dev

script:
    - git clone https://github.com/pytraj/pytraj
    - cp test_list.sh pytraj/tests/
    - cp test_list_example.sh pytraj/examples/
    - cd ./pytraj/tests
    - python ./run_simple_test.py
    - sh test_list.sh
    - cd ../examples
    - sh test_list_example.sh

notifications:
  email: false
