language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
env:
    matrix:
        - PYTHON_VERSION=2.7 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.4 CYTHON_VERSION=0.23
        - PYTHON_VERSION=3.5 CYTHON_VERSION=0.23

install:
    - source setup_env.sh 
    #- conda install cython=$CYTHON_VERSION --yes
    #- conda install --yes libgfortran 
    - conda install --yes nose coverage cython
script:
    - git clone https://github.com/amber-md/pytraj
    - cd pytraj
    - python setup.py install
    - python runtests.py -x

notifications:
  email: false
